[package]
name = "encoding_c"
description = "C API for encoding_rs"
version = "0.9.6"
authors = ["Henri Sivonen <hsivonen@hsivonen.fi>"]
license = "MIT/Apache-2.0"
readme = "README.md"
documentation = "https://docs.rs/encoding_c/"
homepage = "https://docs.rs/encoding_c/"
repository = "https://github.com/hsivonen/encoding_c"
keywords = ["ffi", "capi", "encoding", "unicode", "charset"]
build = "build.rs"
links = "encoding_c"

[features]
simd-accel = ["encoding_rs/simd-accel"]
less-slow-kanji-encode = ["encoding_rs/less-slow-kanji-encode"]
less-slow-big5-hanzi-encode = ["encoding_rs/less-slow-big5-hanzi-encode"]
less-slow-gb-hanzi-encode = ["encoding_rs/less-slow-gb-hanzi-encode"]
fast-hangul-encode = ["encoding_rs/fast-hangul-encode"]
fast-hanja-encode = ["encoding_rs/fast-hanja-encode"]
fast-kanji-encode = ["encoding_rs/fast-kanji-encode"]
fast-gb-hanzi-encode = ["encoding_rs/fast-gb-hanzi-encode"]
fast-big5-hanzi-encode = ["encoding_rs/fast-big5-hanzi-encode"]
fast-legacy-encode = ["encoding_rs/fast-legacy-encode"]

[dependencies]
encoding_rs = "0.8.20"

# Uncomment the lines below to re-run cheddar.
# [build-dependencies]
# rusty-cheddar = "0.3.3"
